version: "3.9"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
      - POSTGRES_DB=db

volumes:
  pg_db: {}
